### ISSUE TITLE
ACD with IOs for testing

### ISSUE THREAD

**Issue by rpabech** [hutcheb/acd#11]
[Test_IO.zip](https://github.com/user-attachments/files/15894604/Test_IO.zip)

See attached Template ACD with IOs

**Comment by hutcheb** [comment]
Yeah, I ran into an issue parsing this as well. It is a problem with the comments database. I have a seperate branch where I'm working on comments but it not quite ready.

I have created a new release which disables it for now (0.1a4) which seems to work now.
![image](https://github.com/hutcheb/acd/assets/15604556/0e5b3b49-0e19-4b18-b729-2d80b0e44543)

**Comment by hutcheb** [comment]
It looks there's some stuff missing from the tag list. This is from my working branch. The hidden tag names get resolved
![image](https://github.com/hutcheb/acd/assets/15604556/c01c403b-8cee-4925-aac1-eea75b9e12a8)

**Comment by rpabech** [comment]
Thanks. Anyluck to get IO card models and firmware?

Thanks

**Comment by rpabech** [comment]
I will send you few more files later tomorrow.

Those will be real project files
