### ISSUE TITLE
Kaitai Struct File

### ISSUE THREAD

**Issue by Vadoola** [hutcheb/acd#4]
Hi I came across this project several months ago, and was interested, but never had time to dig into it much. About 1-2 months ago I had a bit of time, and noticed this project hadn't been updated in a while. Thinking this project might be dead, I actually started digging through your code, and building a Kaitai Struct File based on it, that I might be able to use later to try and change/expand/make my own version of this library.

I notice now that the project isn't dead, just was on hiatus, and while I haven't finished these Kaitai Struct files, they still might be useful (and maybe I will get some time to keep working on them). I was wondering if you might be interested in adding them to your repo, or if you think you would use them at all?

If you aren't familiar [Katai Struct](https://kaitai.io/#what-is-it), you essentially create a YAML file describing a binary file format. You can use the [IDE](https://ide.kaitai.io/) to visualize files as you work on the YAML file. I find it useful when reverse engineering file formats.

You can then use the Katai Struct compiler to generate parsing code in a bunch of different languages, including Python.

Let me know if you are interested, and I'll see if I can clean them up a bit and do a pull request. I've been meaning to clean them up and make the repo public but I just haven't had a chance.

**Comment by hutcheb** [comment]
Hi Vadoola,

Not dead yet, my interest in it comes and goes though.

Definitely interested to see an implementation using Kaitai. I haven’t worked with that library before, it’s looks very interesting.

Even if it’s just a draft PR, I’d have enough motivation in trying out Kaitai to move it along a little bit.

Thanks for the interest 😀

Ben

**Comment by Vadoola** [comment]
I started with the sbregion.dat files, and its the only one I've done much with. I'll see if I can do a bit more work, clean it up and submit a PR sometime soon.

**Comment by Vadoola** [comment]
I'll go ahead and close this after some of the recent changes and merging of my pull request.
